test_med/app/booking/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from views import BookOnline, RecordsWeekJson

urlpatterns = patterns('',
    url(r'^book-online/$', BookOnline.as_view(), name='book_online'),
    url(r'^get-days-for-booking/$', RecordsWeekJson.as_view(), name='get_days_for_booking'),
)

test_med/app/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

from app.booking import urls as booking_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', TemplateView.as_view(template_name='app/front_page.html'), name='front_page'),
    url(r'^booking/', include(booking_urls, namespace='booking')),
]

test_med/app/templates/app/front_page.html
{% extends "app/layout.html" %}

{% block content %}
    <div class="row">
        <div class="v-center text-center">
            <a href="{% url "booking:book_online" %}" class="btn btn-lg btn-primary">Записаться к врачу</a>
        </div>
    </div>
{% endblock %}

test_med/app/templates/app/layout.html
{% load static %}

<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
        <title>Тестовое задание от Дмитрия Колдунова</title>

        {% block scripts %}
            {# <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css"> #}
            {# <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script> #}
            <script src="{% static "jquery/dist/jquery.min.js" %}"></script>
            <script src="{% static "bootstrap/dist/js/bootstrap.min.js" %}"></script>
            <link rel="stylesheet" href="{% static "bootstrap/dist/css/bootstrap.min.css" %}">

            <script src="{% static "angular/angular.min.js" %}"></script>

            <link rel="stylesheet" type="text/css" media="all" href="{% static "app/css/main.css" %}" />
        {% endblock %}
    </head>
    <body>
        <div class="container-fluid">
            {% if messages %}
                <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }} bg-{{ message.tags }}"{% endif %}>
                        {{ message }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}

            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>